"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['theochrone.py']
DATA_FILES = []
OPTIONS = {'argv_emulation':True,'packages':'gui','includes':'imagines',
        'resources':'data,i18n,icons'}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)

