# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-22 06:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HelpArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('version_major', models.PositiveSmallIntegerField()),
                ('version_minor', models.PositiveSmallIntegerField()),
                ('version_patch', models.PositiveSmallIntegerField()),
                ('modification_date', models.DateTimeField(auto_now=True)),
                ('published', models.BooleanField(default=False)),
                ('slug', models.SlugField(max_length=30)),
                ('text', models.TextField()),
                ('short_description', models.CharField(max_length=100)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='help.HelpArticle')),
            ],
        ),
    ]
