# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-23 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0002_auto_20180123_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helparticle',
            name='version_major',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='helparticle',
            name='version_minor',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='helparticle',
            name='version_patch',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
