# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-24 18:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0006_auto_20180124_0537'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='helparticle',
            options={'ordering': ['title'], 'verbose_name': 'Help Article'},
        ),
    ]
