# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-25 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0007_auto_20180124_1825'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='helparticle',
            options={'ordering': ['arbitrary_order', 'title'], 'verbose_name': 'Help Article'},
        ),
        migrations.AddField(
            model_name='helparticle',
            name='arbitrary_order',
            field=models.IntegerField(default=0),
        ),
    ]
