# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-05 04:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0008_auto_20180125_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helparticle',
            name='version',
            field=models.CharField(default='0.6.0', max_length=5),
        ),
    ]
